#!/usr/bin/env python3
"""
Generate sim/rf_init_gates.vh, which holds the register file at zero through
reset in a gate-level simulation.

    python3 scripts/mk_rf_init.py runs/06-clk3p9/out/pipelined_cpu_core_netlist.v

WHY THIS IS GENERATED RATHER THAN WRITTEN BY HAND

The register file's flops have no reset, because reg_file.v initialises RF in
an `initial` block and synthesis ignores those. The netlist therefore comes up
X, exactly as real silicon would, and this program reads x18 before writing it.

The fix is to force the register nets to zero through reset. Their names come
out of synthesis, not out of the RTL, so they are read back out of the netlist
here instead of being assumed. If Genus ever renames or re-groups them, this
script produces a different file rather than a stale one that still compiles
against names that have moved.

Runs on Python 3.6, which is what nanoHUB has.
"""

import argparse
import re
import sys
from pathlib import Path

BS = chr(92)  # a literal backslash, by code point, so no escape can eat it

# A register-file flop INSTANCE, e.g.  \registers_RF_reg[7][0]
#
# THE INSTANCE, NOT THE NET IT DRIVES. The two netlists in this flow name their
# nets completely differently: Genus writes a 32-bit vector \registers_RF[24],
# and Innovus writes it bit-blasted as registers_RF_24_0 -- and where post-route
# optimisation cloned a buffer, as FE_OCPN1417_registers_RF_23__0. An earlier
# version of this script matched the Genus spelling, found 30 of 31 registers in
# the routed netlist, and would have left one of them at X with no warning at
# all. Instance names survive both tools unchanged, so they are what is matched,
# and the force lands on the flop's Q pin.
INST = re.compile(re.escape(BS) + r"(registers_RF_reg\[(\d+)\]\[(\d+)\])")


def find_flops(netlist_text):
    """Every register-file flop instance, ordered by register then bit."""
    found = {}
    for name, reg, bit in INST.findall(netlist_text):
        found[(int(reg), int(bit))] = name
    return [found[k] for k in sorted(found)]


def find_scope(netlist_text):
    """
    The instance path from the testbench down to the module holding the flops.

    reg_file is ungrouped into pipelined_cpu_datapath during synthesis, so the
    nets live in the datapath, and the datapath is instantiated in the core
    under whatever name the RTL gave it. Read that name rather than assume it.
    """
    m = re.search(r"^\s*pipelined_cpu_datapath\s+(\w+)\s*\(", netlist_text, re.M)
    return "u_cpu." + (m.group(1) if m else "datapath")


HEADER = """//*****************************************************************************
// Hold the register file at zero through reset, for GATE-LEVEL simulation only.
//
// GENERATED by scripts/mk_rf_init.py. Do not hand-edit.
//   source netlist : {src}
//   flops forced   : {n}
//
// WHY THIS IS NEEDED
//   reg_file.v zeroes RF in an `initial` block. Simulation honours it and
//   SYNTHESIS IGNORES IT, so the netlist's register-file flops have no reset
//   and come up X. Real silicon behaves the same way: a register file powers
//   up holding whatever it holds.
//
//   It bites this program at instruction 25, `add x18, x18, x17`, which READS
//   x18 BEFORE ANYTHING HAS WRITTEN IT. In RTL the initial block hides that.
//   In gates x18 is X and the loop accumulates X into the result.
//
// WHAT IT DOES
//   Forces the architectural register nets to zero while reset is asserted,
//   then releases them before the first writeback so the CPU drives them
//   normally. This is the standard gate-level treatment of un-resettable
//   state. It is not papering over the problem: run WITHOUT +define+GATE_SIM
//   to watch the X propagate instead.
//
//   x0 has no flops. RISC-V hardwires it to zero, which is why the netlist
//   holds 992 = 31 x 32 register bits and not 1024, and why this starts at 1.
//
// PATH
//   {scope}.{bs}registers_RF_reg[R][B] .Q  -- the flop's output pin. Escaped
//   identifiers are terminated by the space before the '.'. The INSTANCE is
//   forced, not the net it drives, because Genus and Innovus name those nets
//   differently and post-route buffering renames them again.
//*****************************************************************************
"""


def build(netlist_path):
    text = Path(netlist_path).read_text(errors="replace")
    flops = find_flops(text)
    if not flops:
        sys.exit("no registers_RF_reg[R][B] instances in {} -- renamed?".format(netlist_path))

    # 31 architectural registers of 32 bits. Any other count means the match is
    # picking up something else or the register file changed shape, and a
    # PARTIAL force is precisely the failure this script exists to prevent: one
    # register left at X, no error anywhere, and a simulation that fails for a
    # reason nobody looks for.
    if len(flops) != 992:
        sys.stderr.write("WARNING: found {} register flops, expected 992\n".format(len(flops)))

    scope = find_scope(text)

    out = [HEADER.format(src=netlist_path, n=len(flops), scope=scope, bs=BS)]
    out.append("task rf_force;")
    out.append("  begin")
    for f in flops:
        out.append("    force {}.{}{} .Q = 1'b0;".format(scope, BS, f))
    out.append("  end")
    out.append("endtask")
    out.append("")
    out.append("task rf_release;")
    out.append("  begin")
    for f in flops:
        out.append("    release {}.{}{} .Q;".format(scope, BS, f))
    out.append("  end")
    out.append("endtask")
    return "\n".join(out) + "\n", len(flops), scope


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("netlist", help="a Verilog netlist from Genus or Innovus")
    ap.add_argument("-o", "--out", default="sim/rf_init_gates.vh")
    args = ap.parse_args()

    text, n, scope = build(args.netlist)
    Path(args.out).write_text(text, encoding="utf-8")
    print("{} register flops under {} -> {}".format(n, scope, args.out))


if __name__ == "__main__":
    main()
